/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteInterface.Interface;

/**
 *
 * @author 03001072180
 */
public class ConfirmacaoSaidaProduto extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmacaoSaidaProduto
     */
    public ConfirmacaoSaidaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConfirmacaoSaidaSim = new javax.swing.JButton();
        ConfirmacaoSaidaNao = new javax.swing.JButton();

        jLabel1.setText("Deseja visualizar quantidade atual?");

        ConfirmacaoSaidaSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/accept.png"))); // NOI18N
        ConfirmacaoSaidaSim.setText("Sim");

        ConfirmacaoSaidaNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/cross.png"))); // NOI18N
        ConfirmacaoSaidaNao.setText("Não");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConfirmacaoSaidaSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmacaoSaidaNao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmacaoSaidaSim)
                    .addComponent(ConfirmacaoSaidaNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmacaoSaidaNao;
    private javax.swing.JButton ConfirmacaoSaidaSim;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
