package PacoteInterface.Interface;

import Funcionalidades.clsDataHora;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafael Oliveira
 */
public class TelaPrincipal extends javax.swing.JFrame {

    clsDataHora objDataHora = new clsDataHora();
    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        initComponents();
    
        jData.setText(objDataHora.MostraData());
        jHora.setText(objDataHora.MostraHora());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaPrincipal = new javax.swing.JTabbedPane();
        abaCadastros = new javax.swing.JPanel();
        abaCadastrosLabelCodigo = new javax.swing.JLabel();
        abaCadastrosCaixaCodigo = new javax.swing.JTextField();
        abaCadastrosCaixaFornecedor = new javax.swing.JComboBox();
        abaCadastrosLabelFornecedor = new javax.swing.JLabel();
        abaCadastrosLabelQuantidade = new javax.swing.JLabel();
        abaCadastrosCaixaQuantidade = new javax.swing.JTextField();
        abaCadastrosLabelNomeDoProduto = new javax.swing.JLabel();
        abaCadastrosCaixaNomeDoProduto = new javax.swing.JTextField();
        abaCadastrosCaixaNotaFiscal = new javax.swing.JTextField();
        abaCadastrosLabelNotaFiscal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        abaCadastroBotaoSalvar = new javax.swing.JButton();
        abaCadastrosBotaoLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        abaConsulta = new javax.swing.JPanel();
        abaConsultaLabelNomeDoProduto = new javax.swing.JLabel();
        abaConsultaCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        abaConsultaBotaoConsultar = new javax.swing.JButton();
        abaConsultaBotaoLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        abaRequisicao = new javax.swing.JPanel();
        abaRequisicaoLabelQuantidade = new javax.swing.JLabel();
        abaRequisicaoCaixaQuantidade = new javax.swing.JTextField();
        abaRequisicaoLabelNomeDoProduto = new javax.swing.JLabel();
        abaRequisicaoCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        abaRequisicaoBotaoRequisitar = new javax.swing.JButton();
        abaRequisicaoBotaoNovoCadastro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        abaSaida = new javax.swing.JPanel();
        abaSaidaLabelCodigo = new javax.swing.JLabel();
        abaSaidaCaixaCodigo = new javax.swing.JTextField();
        abaSaidaLabelQuantidade = new javax.swing.JLabel();
        abaSaidaCaixaQuantidade = new javax.swing.JTextField();
        abaSaidaLabelNomeDoProduto = new javax.swing.JLabel();
        abaSaidaCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        abaSaidaBotaoEnviar = new javax.swing.JButton();
        jHora = new javax.swing.JLabel();
        jData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu botaoArquivo = new javax.swing.JMenu();
        botaoGerenciamento = new javax.swing.JMenu();
        botaoUsuario = new javax.swing.JMenu();
        botaoUsuarioNovo = new javax.swing.JMenuItem();
        botaoUsuarioEditar = new javax.swing.JMenuItem();
        botaoSobre = new javax.swing.JMenu();
        botaoSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abaCadastrosLabelCodigo.setText("Código");

        abaCadastrosCaixaFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        abaCadastrosCaixaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaCadastrosCaixaFornecedorActionPerformed(evt);
            }
        });

        abaCadastrosLabelFornecedor.setText("Fornecedor");

        abaCadastrosLabelQuantidade.setText("Quantidade");

        abaCadastrosLabelNomeDoProduto.setText("Nome do Produto");

        abaCadastrosLabelNotaFiscal.setText("Nota Fiscal");

        abaCadastroBotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/disk.png"))); // NOI18N
        abaCadastroBotaoSalvar.setText("Salvar");

        abaCadastrosBotaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/page.png"))); // NOI18N
        abaCadastrosBotaoLimpar.setText("Limpar");

        javax.swing.GroupLayout abaCadastrosLayout = new javax.swing.GroupLayout(abaCadastros);
        abaCadastros.setLayout(abaCadastrosLayout);
        abaCadastrosLayout.setHorizontalGroup(
            abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(abaCadastrosLayout.createSequentialGroup()
                        .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaCadastrosLabelCodigo)
                            .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(abaCadastrosCaixaCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(abaCadastrosLabelQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(abaCadastrosCaixaQuantidade, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastrosLayout.createSequentialGroup()
                                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abaCadastrosLabelFornecedor)
                                    .addComponent(abaCadastrosCaixaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abaCadastrosCaixaNotaFiscal)
                                    .addGroup(abaCadastrosLayout.createSequentialGroup()
                                        .addComponent(abaCadastrosLabelNotaFiscal)
                                        .addGap(0, 98, Short.MAX_VALUE))))
                            .addGroup(abaCadastrosLayout.createSequentialGroup()
                                .addComponent(abaCadastrosLabelNomeDoProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(abaCadastrosCaixaNomeDoProduto, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abaCadastrosBotaoLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(abaCadastroBotaoSalvar)))
                .addContainerGap())
        );
        abaCadastrosLayout.setVerticalGroup(
            abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaCadastrosLabelCodigo)
                    .addComponent(abaCadastrosLabelFornecedor)
                    .addComponent(abaCadastrosLabelNotaFiscal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abaCadastrosCaixaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(abaCadastrosCaixaNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(abaCadastrosCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abaCadastrosLabelNomeDoProduto)
                    .addComponent(abaCadastrosLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaCadastrosCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaCadastrosCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaCadastroBotaoSalvar)
                    .addComponent(abaCadastrosBotaoLimpar))
                .addContainerGap())
        );

        abaPrincipal.addTab("Cadastros", new javax.swing.ImageIcon("C:\\Users\\03001072180\\Documents\\NetBeansProjects\\SisLog\\PRODUTO\\src\\PacoteInterface\\icons\\application_add.png"), abaCadastros); // NOI18N

        abaConsultaLabelNomeDoProduto.setText("Nome do Produto");

        abaConsultaBotaoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/find.png"))); // NOI18N
        abaConsultaBotaoConsultar.setText("Consultar");

        abaConsultaBotaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/page.png"))); // NOI18N
        abaConsultaBotaoLimpar.setText("Limpar");

        javax.swing.GroupLayout abaConsultaLayout = new javax.swing.GroupLayout(abaConsulta);
        abaConsulta.setLayout(abaConsultaLayout);
        abaConsultaLayout.setHorizontalGroup(
            abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaConsultaLayout.createSequentialGroup()
                        .addComponent(abaConsultaLabelNomeDoProduto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(abaConsultaCaixaNomeDoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaConsultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abaConsultaBotaoLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(abaConsultaBotaoConsultar)))
                .addContainerGap())
        );
        abaConsultaLayout.setVerticalGroup(
            abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaConsultaLabelNomeDoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abaConsultaCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(abaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaConsultaBotaoConsultar)
                    .addComponent(abaConsultaBotaoLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Consulta", jPanel2);

        abaRequisicaoLabelQuantidade.setText("Quantidade");

        abaRequisicaoLabelNomeDoProduto.setText("Nome do Produto");

        abaRequisicaoBotaoRequisitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/arrow_redo.png"))); // NOI18N
        abaRequisicaoBotaoRequisitar.setText("Requisitar");

        abaRequisicaoBotaoNovoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/add.png"))); // NOI18N
        abaRequisicaoBotaoNovoCadastro.setText("Novo Cadastro");

        javax.swing.GroupLayout abaRequisicaoLayout = new javax.swing.GroupLayout(abaRequisicao);
        abaRequisicao.setLayout(abaRequisicaoLayout);
        abaRequisicaoLayout.setHorizontalGroup(
            abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRequisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaRequisicaoLayout.createSequentialGroup()
                        .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaRequisicaoLayout.createSequentialGroup()
                                .addComponent(abaRequisicaoLabelNomeDoProduto)
                                .addGap(0, 450, Short.MAX_VALUE))
                            .addComponent(abaRequisicaoCaixaNomeDoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaRequisicaoCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaRequisicaoLabelQuantidade)))
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaRequisicaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abaRequisicaoBotaoNovoCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(abaRequisicaoBotaoRequisitar)))
                .addContainerGap())
        );
        abaRequisicaoLayout.setVerticalGroup(
            abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRequisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaRequisicaoLabelNomeDoProduto)
                    .addComponent(abaRequisicaoLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaRequisicaoCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaRequisicaoCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(abaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaRequisicaoBotaoRequisitar)
                    .addComponent(abaRequisicaoBotaoNovoCadastro))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Requisição", jPanel3);

        abaSaidaLabelCodigo.setText("Código");

        abaSaidaLabelQuantidade.setText("Quantidade");

        abaSaidaLabelNomeDoProduto.setText("Nome do Produto");

        abaSaidaCaixaNomeDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaSaidaCaixaNomeDoProdutoActionPerformed(evt);
            }
        });

        abaSaidaBotaoEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/arrow_redo.png"))); // NOI18N
        abaSaidaBotaoEnviar.setText("Enviar");

        javax.swing.GroupLayout abaSaidaLayout = new javax.swing.GroupLayout(abaSaida);
        abaSaida.setLayout(abaSaidaLayout);
        abaSaidaLayout.setHorizontalGroup(
            abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaSaidaLayout.createSequentialGroup()
                        .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaSaidaCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaSaidaLabelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaSaidaLayout.createSequentialGroup()
                                .addComponent(abaSaidaLabelNomeDoProduto)
                                .addGap(0, 371, Short.MAX_VALUE))
                            .addComponent(abaSaidaCaixaNomeDoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaSaidaCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaSaidaLabelQuantidade)))
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaSaidaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abaSaidaBotaoEnviar)))
                .addContainerGap())
        );
        abaSaidaLayout.setVerticalGroup(
            abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaSaidaLabelCodigo)
                    .addComponent(abaSaidaLabelNomeDoProduto)
                    .addComponent(abaSaidaLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaSaidaCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaSaidaCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaSaidaCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(abaSaidaBotaoEnviar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(abaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Saída", jPanel4);

        jHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/clock.png"))); // NOI18N
        jHora.setText(objDataHora.MostraData());

        jData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/calendar_1.png"))); // NOI18N
        jData.setText(objDataHora.MostraData());

        botaoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/computer.png"))); // NOI18N
        botaoArquivo.setText("Arquivo");
        jMenuBar1.add(botaoArquivo);

        botaoGerenciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/cog.png"))); // NOI18N
        botaoGerenciamento.setText("Gerenciamento");

        botaoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/user_business.png"))); // NOI18N
        botaoUsuario.setText("Usuário");

        botaoUsuarioNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/user_silhouette.png"))); // NOI18N
        botaoUsuarioNovo.setText("Novo");
        botaoUsuario.add(botaoUsuarioNovo);

        botaoUsuarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/application_edit.png"))); // NOI18N
        botaoUsuarioEditar.setText("Editar");
        botaoUsuario.add(botaoUsuarioEditar);

        botaoGerenciamento.add(botaoUsuario);

        jMenuBar1.add(botaoGerenciamento);

        botaoSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/exclamation.png"))); // NOI18N
        botaoSobre.setText("Sobre");
        jMenuBar1.add(botaoSobre);

        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteInterface/icones/door_in.png"))); // NOI18N
        botaoSair.setText("Sair");
        jMenuBar1.add(botaoSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jData)
                .addGap(18, 18, 18)
                .addComponent(jHora))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHora)
                    .addComponent(jData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abaPrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abaCadastrosCaixaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaCadastrosCaixaFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abaCadastrosCaixaFornecedorActionPerformed

    private void abaSaidaCaixaNomeDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaSaidaCaixaNomeDoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abaSaidaCaixaNomeDoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abaCadastroBotaoSalvar;
    private javax.swing.JPanel abaCadastros;
    private javax.swing.JButton abaCadastrosBotaoLimpar;
    private javax.swing.JTextField abaCadastrosCaixaCodigo;
    private javax.swing.JComboBox abaCadastrosCaixaFornecedor;
    private javax.swing.JTextField abaCadastrosCaixaNomeDoProduto;
    private javax.swing.JTextField abaCadastrosCaixaNotaFiscal;
    private javax.swing.JTextField abaCadastrosCaixaQuantidade;
    private javax.swing.JLabel abaCadastrosLabelCodigo;
    private javax.swing.JLabel abaCadastrosLabelFornecedor;
    private javax.swing.JLabel abaCadastrosLabelNomeDoProduto;
    private javax.swing.JLabel abaCadastrosLabelNotaFiscal;
    private javax.swing.JLabel abaCadastrosLabelQuantidade;
    private javax.swing.JPanel abaConsulta;
    private javax.swing.JButton abaConsultaBotaoConsultar;
    private javax.swing.JButton abaConsultaBotaoLimpar;
    private javax.swing.JTextField abaConsultaCaixaNomeDoProduto;
    private javax.swing.JLabel abaConsultaLabelNomeDoProduto;
    private javax.swing.JTabbedPane abaPrincipal;
    private javax.swing.JPanel abaRequisicao;
    private javax.swing.JButton abaRequisicaoBotaoNovoCadastro;
    private javax.swing.JButton abaRequisicaoBotaoRequisitar;
    private javax.swing.JTextField abaRequisicaoCaixaNomeDoProduto;
    private javax.swing.JTextField abaRequisicaoCaixaQuantidade;
    private javax.swing.JLabel abaRequisicaoLabelNomeDoProduto;
    private javax.swing.JLabel abaRequisicaoLabelQuantidade;
    private javax.swing.JPanel abaSaida;
    private javax.swing.JButton abaSaidaBotaoEnviar;
    private javax.swing.JTextField abaSaidaCaixaCodigo;
    private javax.swing.JTextField abaSaidaCaixaNomeDoProduto;
    private javax.swing.JTextField abaSaidaCaixaQuantidade;
    private javax.swing.JLabel abaSaidaLabelCodigo;
    private javax.swing.JLabel abaSaidaLabelNomeDoProduto;
    private javax.swing.JLabel abaSaidaLabelQuantidade;
    private javax.swing.JMenu botaoGerenciamento;
    private javax.swing.JMenu botaoSair;
    private javax.swing.JMenu botaoSobre;
    private javax.swing.JMenu botaoUsuario;
    private javax.swing.JMenuItem botaoUsuarioEditar;
    private javax.swing.JMenuItem botaoUsuarioNovo;
    private javax.swing.JLabel jData;
    private javax.swing.JLabel jHora;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
