package PacoteInterface.Interface;

import Funcionalidades.clsDataHora;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rafael Oliveira
 */
public class TelaPrincipal extends javax.swing.JFrame {

    clsDataHora objDataHora = new clsDataHora();
    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        initComponents();
    
        jData.setText(objDataHora.MostraData());
        jHora.setText(objDataHora.MostraHora());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaPrincipal = new javax.swing.JTabbedPane();
        abaCadastros = new javax.swing.JPanel();
        abaCadastrosLabelCodigo = new javax.swing.JLabel();
        abaCadastrosCaixaCodigo = new javax.swing.JTextField();
        abaCadastrosCaixaFornecedor = new javax.swing.JComboBox();
        abaCadastrosLabelFornecedor = new javax.swing.JLabel();
        abaCadastrosLabelQuantidade = new javax.swing.JLabel();
        abaCadastrosCaixaQuantidade = new javax.swing.JTextField();
        abaCadastrosLabelNomeDoProduto = new javax.swing.JLabel();
        abaCadastrosCaixaNomeDoProduto = new javax.swing.JTextField();
        abaCadastrosCaixaNotaFiscal = new javax.swing.JTextField();
        abaCadastrosLabelNotaFiscal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        AbaConsulta = new javax.swing.JPanel();
        abaConsultaLabelNomeDoProduto = new javax.swing.JLabel();
        abaConsultaCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        AbaRequisicao = new javax.swing.JPanel();
        abaRequisicaoLabelQuantidade = new javax.swing.JLabel();
        abaRequisicaoCaixaQuantidade = new javax.swing.JTextField();
        abaRequisicaoLabelNomeDoProduto = new javax.swing.JLabel();
        abaRequisicaoCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        AbaSaida = new javax.swing.JPanel();
        abaSaidaLabelCodigo = new javax.swing.JLabel();
        abaSaidaCaixaCodigo = new javax.swing.JTextField();
        abaSaidaLabelQuantidade = new javax.swing.JLabel();
        abaSaidaCaixaQuantidade = new javax.swing.JTextField();
        abaSaidaLabelNomeDoProduto = new javax.swing.JLabel();
        abaSaidaCaixaNomeDoProduto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jHora = new javax.swing.JLabel();
        jData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu botaoArquivo = new javax.swing.JMenu();
        botaoGerenciamento = new javax.swing.JMenu();
        botaoUsuario = new javax.swing.JMenu();
        botaoUsuarioNovo = new javax.swing.JMenuItem();
        botaoUsuarioEditar = new javax.swing.JMenuItem();
        botaoSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abaCadastrosLabelCodigo.setText("Código");

        abaCadastrosCaixaFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        abaCadastrosCaixaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaCadastrosCaixaFornecedorActionPerformed(evt);
            }
        });

        abaCadastrosLabelFornecedor.setText("Fornecedor");

        abaCadastrosLabelQuantidade.setText("Quantidade");

        abaCadastrosLabelNomeDoProduto.setText("Nome do Produto");

        abaCadastrosLabelNotaFiscal.setText("Nota Fiscal");

        javax.swing.GroupLayout abaCadastrosLayout = new javax.swing.GroupLayout(abaCadastros);
        abaCadastros.setLayout(abaCadastrosLayout);
        abaCadastrosLayout.setHorizontalGroup(
            abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(abaCadastrosLayout.createSequentialGroup()
                        .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaCadastrosLabelCodigo)
                            .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(abaCadastrosCaixaCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(abaCadastrosLabelQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(abaCadastrosCaixaQuantidade, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastrosLayout.createSequentialGroup()
                                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abaCadastrosLabelFornecedor)
                                    .addComponent(abaCadastrosCaixaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abaCadastrosCaixaNotaFiscal)
                                    .addGroup(abaCadastrosLayout.createSequentialGroup()
                                        .addComponent(abaCadastrosLabelNotaFiscal)
                                        .addGap(0, 98, Short.MAX_VALUE))))
                            .addGroup(abaCadastrosLayout.createSequentialGroup()
                                .addComponent(abaCadastrosLabelNomeDoProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(abaCadastrosCaixaNomeDoProduto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        abaCadastrosLayout.setVerticalGroup(
            abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaCadastrosLabelCodigo)
                    .addComponent(abaCadastrosLabelFornecedor)
                    .addComponent(abaCadastrosLabelNotaFiscal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abaCadastrosCaixaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(abaCadastrosCaixaNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(abaCadastrosCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abaCadastrosLabelNomeDoProduto)
                    .addComponent(abaCadastrosLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaCadastrosCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaCadastrosCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        abaPrincipal.addTab("Cadastros", abaCadastros);

        abaConsultaLabelNomeDoProduto.setText("Nome do Produto");

        javax.swing.GroupLayout AbaConsultaLayout = new javax.swing.GroupLayout(AbaConsulta);
        AbaConsulta.setLayout(AbaConsultaLayout);
        AbaConsultaLayout.setHorizontalGroup(
            AbaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaConsultaLayout.createSequentialGroup()
                        .addComponent(abaConsultaLabelNomeDoProduto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(abaConsultaCaixaNomeDoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        AbaConsultaLayout.setVerticalGroup(
            AbaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaConsultaLabelNomeDoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abaConsultaCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Consulta", jPanel2);

        abaRequisicaoLabelQuantidade.setText("Quantidade");

        abaRequisicaoLabelNomeDoProduto.setText("Nome do Produto");

        javax.swing.GroupLayout AbaRequisicaoLayout = new javax.swing.GroupLayout(AbaRequisicao);
        AbaRequisicao.setLayout(AbaRequisicaoLayout);
        AbaRequisicaoLayout.setHorizontalGroup(
            AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaRequisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaRequisicaoLayout.createSequentialGroup()
                        .addGroup(AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaRequisicaoLayout.createSequentialGroup()
                                .addComponent(abaRequisicaoLabelNomeDoProduto)
                                .addGap(0, 450, Short.MAX_VALUE))
                            .addComponent(abaRequisicaoCaixaNomeDoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaRequisicaoCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaRequisicaoLabelQuantidade)))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        AbaRequisicaoLayout.setVerticalGroup(
            AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaRequisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaRequisicaoLabelNomeDoProduto)
                    .addComponent(abaRequisicaoLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbaRequisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaRequisicaoCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaRequisicaoCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Requisição", jPanel3);

        abaSaidaLabelCodigo.setText("Código");

        abaSaidaLabelQuantidade.setText("Quantidade");

        abaSaidaLabelNomeDoProduto.setText("Nome do Produto");

        abaSaidaCaixaNomeDoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaSaidaCaixaNomeDoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaSaidaLayout = new javax.swing.GroupLayout(AbaSaida);
        AbaSaida.setLayout(AbaSaidaLayout);
        AbaSaidaLayout.setHorizontalGroup(
            AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaSaidaLayout.createSequentialGroup()
                        .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaSaidaCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaSaidaLabelCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AbaSaidaLayout.createSequentialGroup()
                                .addComponent(abaSaidaLabelNomeDoProduto)
                                .addGap(0, 371, Short.MAX_VALUE))
                            .addComponent(abaSaidaCaixaNomeDoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abaSaidaCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abaSaidaLabelQuantidade)))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        AbaSaidaLayout.setVerticalGroup(
            AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaSaidaLabelCodigo)
                    .addComponent(abaSaidaLabelNomeDoProduto)
                    .addComponent(abaSaidaLabelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaSaidaCaixaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaSaidaCaixaNomeDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abaSaidaCaixaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(AbaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        abaPrincipal.addTab("Saída", jPanel4);

        jHora.setText(jHora);

        jData.setText(jData);

        botaoArquivo.setText("Arquivo");
        jMenuBar1.add(botaoArquivo);

        botaoGerenciamento.setText("Gerenciamento");

        botaoUsuario.setText("Usuário");

        botaoUsuarioNovo.setText("Novo");
        botaoUsuario.add(botaoUsuarioNovo);

        botaoUsuarioEditar.setText("Editar");
        botaoUsuario.add(botaoUsuarioEditar);

        botaoGerenciamento.add(botaoUsuario);

        jMenuBar1.add(botaoGerenciamento);

        botaoSair.setText("Sair");
        jMenuBar1.add(botaoSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abaPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jData)
                .addGap(18, 18, 18)
                .addComponent(jHora))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHora)
                    .addComponent(jData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abaPrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abaCadastrosCaixaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaCadastrosCaixaFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abaCadastrosCaixaFornecedorActionPerformed

    private void abaSaidaCaixaNomeDoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaSaidaCaixaNomeDoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abaSaidaCaixaNomeDoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaConsulta;
    private javax.swing.JPanel AbaRequisicao;
    private javax.swing.JPanel AbaSaida;
    private javax.swing.JPanel abaCadastros;
    private javax.swing.JTextField abaCadastrosCaixaCodigo;
    private javax.swing.JComboBox abaCadastrosCaixaFornecedor;
    private javax.swing.JTextField abaCadastrosCaixaNomeDoProduto;
    private javax.swing.JTextField abaCadastrosCaixaNotaFiscal;
    private javax.swing.JTextField abaCadastrosCaixaQuantidade;
    private javax.swing.JLabel abaCadastrosLabelCodigo;
    private javax.swing.JLabel abaCadastrosLabelFornecedor;
    private javax.swing.JLabel abaCadastrosLabelNomeDoProduto;
    private javax.swing.JLabel abaCadastrosLabelNotaFiscal;
    private javax.swing.JLabel abaCadastrosLabelQuantidade;
    private javax.swing.JTextField abaConsultaCaixaNomeDoProduto;
    private javax.swing.JLabel abaConsultaLabelNomeDoProduto;
    private javax.swing.JTabbedPane abaPrincipal;
    private javax.swing.JTextField abaRequisicaoCaixaNomeDoProduto;
    private javax.swing.JTextField abaRequisicaoCaixaQuantidade;
    private javax.swing.JLabel abaRequisicaoLabelNomeDoProduto;
    private javax.swing.JLabel abaRequisicaoLabelQuantidade;
    private javax.swing.JTextField abaSaidaCaixaCodigo;
    private javax.swing.JTextField abaSaidaCaixaNomeDoProduto;
    private javax.swing.JTextField abaSaidaCaixaQuantidade;
    private javax.swing.JLabel abaSaidaLabelCodigo;
    private javax.swing.JLabel abaSaidaLabelNomeDoProduto;
    private javax.swing.JLabel abaSaidaLabelQuantidade;
    private javax.swing.JMenu botaoGerenciamento;
    private javax.swing.JMenu botaoSair;
    private javax.swing.JMenu botaoUsuario;
    private javax.swing.JMenuItem botaoUsuarioEditar;
    private javax.swing.JMenuItem botaoUsuarioNovo;
    private javax.swing.JLabel jData;
    private javax.swing.JLabel jHora;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
